### ISSUE TITLE
Hi Ross and Vinay, I am using VTrack to analyse my acoustic telemetry VEMCO data. Since updating R and R tools to the most recent versions (4.0) I get an error when using the setupData function to create my ATT data: "Error in setupData(Tag.Detections = VEMCOdata, Tag.Metadata = taginfo,  :    could not find function "setupData". I have re-installed the VTrack package also but still get the error. Any help would be greatly appreciated. Thanks very much

### ISSUE THREAD

**Issue by Molly-Scott** [RossDwyer/VTrack#16]

**Comment by vinayudyawer** [comment]
Hi Molly, 
Thanks for emailing through the issue. 
Just to resolve it here for other users, the new functions in VTrack i.e. `setupData()` requires the development version of the package. To access these functions you will need to install it via Github:

`remove.packages("VTrack")

require("devtools")
devtools::install_github("ross dwyer/VTrack")`


The installation process will ask you to update other dependencies, which you should. However there seems to be an error when updating the 'glue' package currently, so for now please don't update this package, otherwise the installation process won't complete successfully.
